import json
from typing import Any, Dict, List

from agno.agent import Agent
from agno.models.openai import OpenAIChat

from config import config
from tools.skill_loader import run_skill
from tools.tool_dispatcher import run_tool


def call_infringement_matcher_subprocess(
    concept: Dict[str, Any], patents: List[Dict[str, Any]]
) -> str:
    """
    Executes the infringement_matcher subprocess to evaluate overlap.
    Args:
        concept: The structured concept JSON dictionary.
        patents: The list of candidate patent dictionaries.
    """
    result = run_tool("infringement_matcher", {"concept": concept, "patents": patents})
    return json.dumps(result)


infringement_matcher = Agent(
    name="Infringement Matcher",
    role="Patent Overlap Analysis",
    model=OpenAIChat(id=config.OPENAI_MODEL, temperature=config.OPENAI_TEMPERATURE),
    description="Evaluates structured claims against candidate patents to determine infringement risk.",
    tools=[run_skill, call_infringement_matcher_subprocess],
    instructions=[
        "You are the Infringement Matcher, a meticulous patent analyst.",
        "Your task is to identify structural overlap between the user's proposed concept and candidate prior art.",
        "",
        "STEP 1: Learn the Rules.",
        " - Call `run_skill` with the argument 'infringement_matcher' to load your scoring thresholds and JSON schema constraints.",
        "",
        "STEP 2: Evaluate Overlap.",
        " - You will be given the original concept JSON and a list of candidate patents.",
        " - Call `call_infringement_matcher_subprocess` and pass these two arguments exactly as they are.",
        " - The subprocess will analyze the semantic similarity and return a scored JSON array.",
        "",
        "STEP 3: Output the Results.",
        " - Return the exact JSON string generated by the subprocess so the Report Drafter has accurate scores to present.",
    ],
)
